spring.application.name=spring-homepage
spring.data.mongodb.database=${env.MONGO_DATABASE}
spring.data.mongodb.uri=mongodb+srv://${env.MONGO_USER}:${env.MONGO_PASSWORD}@${env.MONGO_CLUSTER}
spring.data.mongodb.host=cluster0.twwoho2.mongodb.net
spring.data.mongodb.port=27017

server.port=8080
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=${env.SSL_KEY_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=springboot


application.security.jwt.secret-key=${env.JWT_SECRET_KEY}
application.security.jwt.expiration=604800000
application.security.jwt.refresh-token.expiration=86400000

spring.security.oauth2.client.registration.google.client-id=${env.GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${env.GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

# GitHub OAuth2 (optional)
spring.security.oauth2.client.registration.github.client-id=${env.GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${env.GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=user:email

logging.level.org.hibernate=DEBUG
logging.level.org.mongodb.driver=DEBUG
#logging.file.name=logs/spring-homepage.log





