package de.nogaemer.springhomepage.main.meals.dto

import com.fasterxml.jackson.annotation.JsonInclude
import de.nogaemer.springhomepage.main.images.Image

/**
 * Lightweight Data Transfer Object for meal list and card displays.
 *
 * This DTO provides a summarized view of meals optimized for list/grid displays,
 * search results, and filtering operations. It contains only essential fields needed
 * for card-style presentations without the full detail of the complete Meal entity.
 *
 * ## Projection Strategy
 * MealCardDto is populated via MongoDB aggregation pipelines that project only the
 * required fields. This reduces data transfer size and improves performance for
 * list operations compared to fetching full Meal entities.
 *
 * ## Optional Fields
 * Fields marked as nullable are conditionally included based on query context:
 * - **relevanceScore/matchingRatio**: Populated by ingredient-based search queries
 * - **matchingIngredients**: Shows which ingredients matched the search criteria
 * - **ingredients**: Full ingredient list for detailed card views
 * - **userRatings**: Populated when filtering by specific user ratings
 *
 * ## Aggregation Usage
 * Generated by aggregation stages in:
 * - [MealService.findAll]: Basic card projection
 * - [MealService.filterMeals]: With userRatings and filtered rating scores
 * - [UnifiedMealSearchService]: With relevance scores and matching ingredients
 *
 * ## JSON Serialization
 * [@JsonInclude] ensures null optional fields are omitted from JSON responses,
 * keeping response payloads minimal.
 *
 * @property id MongoDB ObjectId as string
 * @property name Display name of the meal
 * @property rating Average user rating (0.0 if no ratings)
 * @property time Preparation and cooking time in minutes
 * @property difficulty Difficulty level
 * @property images Optional list of meal images for card display
 * @property instructions Optional cooking instructions (included in detailed views)
 * @property relevanceScore Optional search relevance score (0.0-1.0)
 * @property matchingRatio Optional ratio of matching ingredients for search queries
 * @property matchingIngredients Optional list of ingredients that matched search criteria
 * @property ingredients Optional complete ingredient list for detailed card displays
 * @property userRatings Optional user-specific ratings when filtering by user
 *
 * @see SimpleMealIngredientDto
 * @see de.nogaemer.springhomepage.main.meals.models.Meal
 * @see MealService.findAll
 * @see MealService.filterMeals
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
data class MealCardDto(
    val id: String,
    val name: String,
    val rating: Double,
    val time: Long,
    val difficulty: String,
    val images: List<Image>? = null,
    val instructions: List<String>? = null,

    // Optional fields for specific filters
    val relevanceScore: Double? = null,
    val matchingRatio: Double? = null,
    val matchingIngredients: List<SimpleMealIngredientDto>? = null,
    val ingredients: List<SimpleMealIngredientDto>? = null,
    val userRatings: List<Any>? = null
)

/**
 * Simplified ingredient representation for meal card displays.
 *
 * This DTO provides a flattened view of meal ingredients, denormalizing the
 * Ingredient and IngredientUnit relationships into simple string fields.
 * This avoids nested object complexity in card views.
 *
 * ## Mapping from MealIngredient
 * - **name**: Copied from MealIngredient.name
 * - **amount**: Copied from MealIngredient.amount
 * - **ingredientName**: Resolved from MealIngredient.ingredient.name
 * - **ingredientCategory**: Resolved from MealIngredient.ingredient.category
 * - **unitAbbreviation**: Resolved from MealIngredient.unit.abbreviation
 * - **unitFullName**: Resolved from MealIngredient.unit.fullName
 *
 * ## Aggregation Source
 * Populated via MongoDB aggregation $map operations that flatten the nested
 * ingredient references into this simplified structure.
 *
 * @property name Display name of the ingredient in recipe context
 * @property amount Quantity as a string (e.g., "500", "1.5", "1/2")
 * @property ingredientName Optional base ingredient name
 * @property ingredientCategory Optional ingredient category (e.g., "Vegetables")
 * @property unitAbbreviation Optional unit abbreviation (e.g., "g", "ml")
 * @property unitFullName Optional full unit name (e.g., "grams", "milliliters")
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
data class SimpleMealIngredientDto(
    val name: String,
    val amount: String,
    val ingredientName: String? = null,
    val ingredientCategory: String? = null,
    val unitAbbreviation: String? = null,
    val unitFullName: String? = null
)

